"""add user favorite

Revision ID: f9c9d11fbffa
Revises: c58f0d0f4efa
Create Date: 2025-02-26 23:20:24.335644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9c9d11fbffa'
down_revision: Union[str, None] = 'c58f0d0f4efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_favorite',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('announcement_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['announcement_id'],
            ['announcement.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_favorite_id'), 'user_favorite', ['id'], unique=False)
    op.create_index(
        op.f('ix_user_favorite_user_id'), 'user_favorite', ['user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorite_user_id'), table_name='user_favorite')
    op.drop_index(op.f('ix_user_favorite_id'), table_name='user_favorite')
    op.drop_table('user_favorite')
    # ### end Alembic commands ###
