"""announcement media

Revision ID: b106dbb8514e
Revises: f9c9d11fbffa
Create Date: 2025-03-01 23:33:26.572738

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b106dbb8514e'
down_revision: Union[str, None] = 'f9c9d11fbffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'announcement_media',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('announcement_id', sa.UUID(), nullable=False),
        sa.Column('file_url', sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ['announcement_id'],
            ['announcement.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_announcement_media_id'), 'announcement_media', ['id'], unique=False
    )
    op.drop_table('announcement_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'announcement_image',
        sa.Column('announcement_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['announcement_id'],
            ['announcement.id'],
            name='announcement_image_announcement_id_fkey',
        ),
        sa.PrimaryKeyConstraint('announcement_id', name='announcement_image_pkey'),
    )
    op.drop_index(op.f('ix_announcement_media_id'), table_name='announcement_media')
    op.drop_table('announcement_media')
    # ### end Alembic commands ###
