"""add announcement discount

Revision ID: c58f0d0f4efa
Revises: a73210a6ca22
Create Date: 2025-02-26 22:46:00.357465

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c58f0d0f4efa'
down_revision: Union[str, None] = 'a73210a6ca22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'announcement', sa.Column('price_with_discount', sa.INTEGER(), nullable=True)
    )
    op.add_column('announcement', sa.Column('discount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcement', 'discount')
    op.drop_column('announcement', 'price_with_discount')
    # ### end Alembic commands ###
