"""initial

Revision ID: a73210a6ca22
Revises:
Create Date: 2025-02-09 15:22:13.442929

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a73210a6ca22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'category',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table(
        'role',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=30), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table(
        'user',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=30), nullable=False),
        sa.Column('second_name', sa.VARCHAR(length=30), nullable=True),
        sa.Column('avatar_url', sa.TEXT(), nullable=True),
        sa.Column('role_id', sa.INTEGER(), nullable=False),
        sa.Column('rating', sa.FLOAT(), nullable=True),
        sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
        sa.Column('email', sa.VARCHAR(length=50), nullable=False),
        sa.Column('hashed_password', sa.TEXT(), nullable=False),
        sa.Column('refresh_tokens', postgresql.ARRAY(sa.TEXT()), nullable=False),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['role.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table(
        'announcement',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=100), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=False),
        sa.Column('price', sa.INTEGER(), nullable=True),
        sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
        sa.Column('status', sa.VARCHAR(length=15), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('category_id', sa.INTEGER(), nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['category.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_announcement_id'), 'announcement', ['id'], unique=False)
    op.create_table(
        'review',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('text', sa.TEXT(), nullable=True),
        sa.Column('user_to_id', sa.UUID(), nullable=False),
        sa.Column('user_from_id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['user_from_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_to_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    op.create_table(
        'announcement_image',
        sa.Column('announcement_id', sa.UUID(), nullable=False),
        sa.Column('image_url', sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ['announcement_id'],
            ['announcement.id'],
        ),
        sa.PrimaryKeyConstraint('announcement_id'),
    )
    sa.insert(
        table_name='role',
        values=[
            {'id': 1, 'name': 'Пользователь'},
            {'id': 2, 'name': 'Менеджер'},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement_image')
    op.drop_index(op.f('ix_review_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_announcement_id'), table_name='announcement')
    op.drop_table('announcement')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
